title: Sarthak Nagapurkar
logo: assets/image/Passport Photo.jpg
theme: jekyll-theme-minimal
remote_theme: just-the-docs/just-the-docs
sidebar:
  - about-me
  - label: About Me
  - my-projects
  - label: My Projects
  - tableau-profile
  - label: My Tableau Portfolio
  
